### ISSUE TITLE
добавити Locales

### ISSUE THREAD

**Issue by ktarasz** [modelism/modelism.github.io#1]
Дивись
https://docs.angularjs.org/guide/i18n
https://github.com/angular/angular.js/blob/master/src/ngLocale/angular-locale_uk.js

**Comment by gvizdyk** [comment]
Додав https://github.com/modelism/modelism.github.io/commit/d269ca652b06e37c613e8f45f642f615ed84323f і https://github.com/modelism/modelism.github.io/commit/6cd823977e14db68f5058f2a66c2954f777a3620

**Comment by ktarasz** [comment]
Є на cdn https://code.angularjs.org/1.3.10/i18n/angular-locale_uk.js

**Comment by gvizdyk** [comment]
Поправив - https://github.com/modelism/modelism.github.io/commit/ee207c60e2b47387cbd88f20ef28ea5967427d81
